---
brews:
  # editors
  - emacs
  - vim
  # languages
  - go
  - maven
  - python
  # misc
  - arp-scan
  - arpack
  - aspcud
  - at-spi2-atk
  - at-spi2-core
  - atk
  - autoconf
  - automake
  - autossh
  - bdw-gc
  - boost
  - brew-cask
  - cairo
  - camlp5
  - clasp
  - cloog
  - cloog-ppl015
  - cmake
  - coreutils
  - cscope
  - ctags
  - d-bus
  - dotwrp
  - elasticsearch
  - fftw
  - findutils
  - fltk
  - fontconfig
  - freetype
  - fuse4x-kext
  - gcc47
  - gd
  - gdbm
  - gdk-pixbuf
  - gettext
  - git
  - glib
  - glpk
  - gmp
  - gmp4
  - gnu-sed
  - gnuplot
  - gnutls
  - gobject-introspection
  - graphicsmagick
  - gringo
  - gtk
  - gtk-engines
  - hadoop
  - harfbuzz
  - hdf5
  - htop-osx
  - hub
  - icu4c
  - intltool
  - isl
  - jasper
  - jpeg
  - jq
  - jython
  - legit
  - leiningen
  - lftp
  - libevent
  - libffi
  - libgpg-error
  - libksba
  - libmpc
  - libmpc08
  - libpng
  - libtasn1
  - libtiff
  - libtool
  - libxml2
  - libxslt
  - libyaml
  - little-cms
  - lua
  - macvim
  - memcached
  - mercurial
  - metis
  - mongodb
  - mpfr
  - mpfr2
  - nettle
  - nginx
  - node
  - objective-caml
  - opam
  - openssl
  - openssl098
  - ossp-uuid
  - osxfuse
  - p11-kit
  - pango
  - pcre
  - pidof
  - pixman
  - pkg-config
  - png2ico
  - ppl011
  - putty
  - qhull
  - qrupdate
  - qt
  - rbenv
  - rbenv-vars
  - re2c
  - readline
  - reattach-to-user-namespace
  - ruby-build
  - sbt
  - scala
  - scons
  - sip
  - sl
  - solr
  - sqlite
  - sshfs
  - suite-sparse
  - szip
  - tbb
  - texinfo
  - the_silver_searcher
  - tmux
  - w3m
  - watch
  - wget
  - xz
  - zlib
  # databases
  - postgres
  - mongodb
  - mysql
  # deployment
  - heroku-toolbelt

taps:
  - caskroom/cask
  - caskroom/fonts
  - homebrew/dupes

casks:
  # editors
  - atom
  - sublime-text
  # fonts
  - font-source-code-pro
  - font-sauce-code-powerline
  # languages
  - haskell-platform
  - java
  - r
  - weka
  # misc
  - adium
  - appcleaner
  - asepsis
  - caffeine
  - dropbox
  - evernote
  - firefox
  - flash
  - google-chrome
  - google-hangouts
  - intellij-idea-ce
  - iterm2
  - mailplane
  - onepassword
  - rstudio
  - slack
  - slate
  - skitch
  - skype
  - spotify
  - vagrant
  - vagrant-manager
  - vlc
  - xquartz
