---
- hosts: all
  roles:

  - role: homebrews
  - role: dotfiles
  - role: vim

  # shell tooling
  - role: git_install
    git_user_name: Matt DeLand
    git_user_email: matthew.deland@gmail.com
  - role: legit
  - role: hub

  - role: rbenv
  - role: python_packages

  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower

  # data tools
  - role: git_package
    repo: github.com/gcapan/recommender
  - role: pyopt

  # osx config
  - role: dock
    apps:
    - "'/Applications/Mailplane 3.app'"
    - "'/Applications/Google Chrome.app'"
    - /Applications/Spotify.app
    - /Applications/iTerm.app
    - /Applications/Asana.app
    - /Applications/Slack.app
    folders:
    - path: ~/
    - path: /Applications
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES
