---
- hosts: all
  roles:

  - role: dotfiles
  # fonts

  - role: vim
  - role: cask_install
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_install
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git_install
    git_user_name: Matt DeLand
    git_user_email: matthew.deland@gmail.com
  - role: legit
  - role: hub
  - role: brew_install
    package_name: vim

  ## languages
  - role: brew_install
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: cask_install
    package_name: java
  - role: brew_install
    package_name: python
  - role: cask_install
    package_name: r
  - role: cask_install
    package_name: haskell-platform
  - role: cask_install
    package_name: weka
  - role: brew_install
    package_name: maven

  ## python librariers
  - role: pip_install
    package_name: beatbox
  - role: pip_install
    package_name: beautifulsoup4
  - role: pip_install
    package_name: Cheetah
  - role: pip_install
    package_name: couchdbkit
  - role: pip_install
    package_name: cvxopt
  - role: pip_install
    package_name: Cython
    sudo: yes
  - role: pip_install
    package_name: gdata
  - role: pip_install
    package_name: gspread
  - role: pip_install
    package_name: html5lib
  - role: pip_install
    package_name: http-parser
  - role: pip_install
    package_name: ipython
  - role: pip_install
    package_name: jedi
  - role: pip_install
    package_name: Jinja2
  - role: pip_install
    package_name: llvmpy
  - role: pip_install
    package_name: lxml
  - role: pip_install
    package_name: Markdown
  - role: pip_install
    package_name: MarkupSafe
  - role: pip_install
    package_name: matplotlib
  - role: pip_install
    package_name: mercurial
  - role: pip_install
    package_name: MySQL-python
  - role: pip_install
    package_name: networkx
  - role: pip_install
    package_name: numba
  - role: pip_install
    package_name: numpy
  - role: pip_install
    package_name: pandas
  - role: pip_install
    package_name: patsy
  - role: pip_install
    package_name: Pattern
  - role: pip_install
    package_name: peewee
  - role: pip_install
    package_name: pip
  - role: pip_install
    package_name: pudb
  - role: pip_install
    package_name: pycurl
  - role: pip_install
    package_name: pygmaps
  - role: pip_install
    package_name: Pygments
  - role: pip_install
    package_name: pymc
  - role: pip_install
    package_name: pymongo
  - role: pip_install
    package_name: PyMySQL
  - role: pip_install
    package_name: pysqlite
  - role: pip_install
    package_name: python-dateutil
  - role: pip_install
    package_name: python-google-places
  - role: pip_install
    package_name: pytz
  - role: pip_install
    package_name: pyzmq
  - role: pip_install
    package_name: readline
  - role: pip_install
    package_name: requests
  - role: pip_install
    package_name: restkit
  - role: pip_install
    package_name: scikit-learn
  - role: pip_install
    package_name: scipy
  - role: pip_install
    package_name: scrapely
  - role: pip_install
    package_name: setuptools
  - role: pip_install
    package_name: six
  - role: pip_install
    package_name: socketpool
  - role: pip_install
    package_name: statsmodels
  - role: pip_install
    package_name: tornado
    upgrade: true
  - role: pip_install
    package_name: urwid
  - role: pip_install
    package_name: w3lib
  - role: pip_install
    package_name: WebOb
  - role: pip_install
    package_name: wsgiref
  - role: pip_install
    package_name: xmltodict

  ## homebrew packages
  - role: brew_install
    package_name: apple-gcc42
  - role: brew_install
    package_name: arp-scan
  - role: brew_install
    package_name: arpack
  - role: brew_install
    package_name: aspcud
  - role: brew_install
    package_name: at-spi2-atk
  - role: brew_install
    package_name: at-spi2-core
  - role: brew_install
    package_name: atk
  - role: brew_install
    package_name: autoconf
  - role: brew_install
    package_name: automake
  - role: brew_install
    package_name: autossh
  - role: brew_install
    package_name: bdw-gc
  - role: brew_install
    package_name: boost
  - role: brew_install
    package_name: brew-cask
  - role: brew_install
    package_name: cairo
  - role: brew_install
    package_name: camlp5
  - role: brew_install
    package_name: clasp
  - role: brew_install
    package_name: cloog
  - role: brew_install
    package_name: cloog-ppl015
  - role: brew_install
    package_name: cmake
  - role: brew_install
    package_name: coreutils
  - role: brew_install
    package_name: cscope
  - role: brew_install
    package_name: ctags
  - role: brew_install
    package_name: d-bus
  - role: brew_install
    package_name: dotwrp
  - role: brew_install
    package_name: elasticsearch
  - role: brew_install
    package_name: fftw
  - role: brew_install
    package_name: findutils
  - role: brew_install
    package_name: fltk
  - role: brew_install
    package_name: fontconfig
  - role: brew_install
    package_name: freetype
  - role: brew_install
    package_name: fuse4x-kext
  - role: brew_install
    package_name: gcc47
  - role: brew_install
    package_name: gd
  - role: brew_install
    package_name: gdbm
  - role: brew_install
    package_name: gdk-pixbuf
  - role: brew_install
    package_name: gettext
  - role: brew_install
    package_name: gfortran
  - role: brew_install
    package_name: git
  - role: brew_install
    package_name: glib
  - role: brew_install
    package_name: glpk
  - role: brew_install
    package_name: gmp
  - role: brew_install
    package_name: gmp4
  - role: brew_install
    package_name: gnu-sed
  - role: brew_install
    package_name: gnuplot
  - role: brew_install
    package_name: gnutls
  - role: brew_install
    package_name: go
  - role: brew_install
    package_name: gobject-introspection
  - role: brew_install
    package_name: graphicsmagick
  - role: brew_install
    package_name: gringo
  - role: brew_install
    package_name: gtk+
  - role: brew_install
    package_name: gtk+3
  - role: brew_install
    package_name: gtk-engines
  - role: brew_install
    package_name: hadoop
  - role: brew_install
    package_name: harfbuzz
  - role: brew_install
    package_name: hdf5
  - role: brew_install
    package_name: htop-osx
  - role: brew_install
    package_name: hub
  - role: brew_install
    package_name: icu4c
  - role: brew_install
    package_name: intltool
  - role: brew_install
    package_name: isl
  - role: brew_install
    package_name: jasper
  - role: brew_install
    package_name: jpeg
  - role: brew_install
    package_name: jython
  - role: brew_install
    package_name: legit
  - role: brew_install
    package_name: leiningen
  - role: brew_install
    package_name: lftp
  - role: brew_install
    package_name: libevent
  - role: brew_install
    package_name: libffi
  - role: brew_install
    package_name: libgpg-error
  - role: brew_install
    package_name: libksba
  - role: brew_install
    package_name: libmpc
  - role: brew_install
    package_name: libmpc08
  - role: brew_install
    package_name: libpng
  - role: brew_install
    package_name: libtasn1
  - role: brew_install
    package_name: libtiff
  - role: brew_install
    package_name: libtool
  - role: brew_install
    package_name: libxml2
  - role: brew_install
    package_name: libxslt
  - role: brew_install
    package_name: libyaml
  - role: brew_install
    package_name: little-cms
  - role: brew_install
    package_name: lua
  - role: brew_install
    package_name: macvim
  - role: brew_install
    package_name: memcached
  - role: brew_install
    package_name: mercurial
  - role: brew_install
    package_name: metis
  - role: brew_install
    package_name: mongodb
  - role: brew_install
    package_name: mpfr
  - role: brew_install
    package_name: mpfr2
  - role: brew_install
    package_name: nettle
  - role: brew_install
    package_name: nginx
  - role: brew_install
    package_name: objective-caml
  - role: brew_install
    package_name: opam
  - role: brew_install
    package_name: openssl
  - role: brew_install
    package_name: openssl098
  - role: brew_install
    package_name: ossp-uuid
  - role: brew_install
    package_name: osxfuse
  - role: brew_install
    package_name: p11-kit
  - role: brew_install
    package_name: pango
  - role: brew_install
    package_name: pcre
  - role: brew_install
    package_name: pidof
  - role: brew_install
    package_name: pixman
  - role: brew_install
    package_name: pkg-config
  - role: brew_install
    package_name: png2ico
  - role: brew_install
    package_name: ppl011
  - role: brew_install
    package_name: putty
  - role: brew_install
    package_name: qhull
  - role: brew_install
    package_name: qrupdate
  - role: brew_install
    package_name: qt
  - role: brew_install
    package_name: rbenv-vars
  - role: brew_install
    package_name: re2c
  - role: brew_install
    package_name: readline
  - role: brew_install
    package_name: reattach-to-user-namespace
  - role: brew_install
    package_name: ruby-build
  - role: brew_install
    package_name: sbt
  - role: brew_install
    package_name: scala
  - role: brew_install
    package_name: scons
  - role: brew_install
    package_name: setup.data
  - role: brew_install
    package_name: sip
  - role: brew_install
    package_name: sl
  - role: brew_install
    package_name: solr
  - role: brew_install
    package_name: sqlite
  - role: brew_install
    package_name: sshfs
  - role: brew_install
    package_name: suite-sparse
  - role: brew_install
    package_name: szip
  - role: brew_install
    package_name: tbb
  - role: brew_install
    package_name: texinfo
  - role: brew_install
    package_name: the_silver_searcher
  - role: brew_install
    package_name: tmux
  - role: brew_install
    package_name: w3m
  - role: brew_install
    package_name: watch
  - role: brew_install
    package_name: wget
  - role: brew_install
    package_name: xz
  - role: brew_install
    package_name: zlib

  ## databases
  - role: brew_install
    package_name: postgres
  - role: brew_install
    package_name: mongodb
  - role: brew_install
    package_name: mysql

  ## deployment
  - role: brew_install
    package_name: heroku-toolbelt
  # - role: brew_install
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_install
    package_name: atom
  - role: cask_install
    package_name: sublime-text

  # data tools
  - role: git_package
    repo: github.com/gcapan/recommender
  - role: pyopt

  # misc
  - role: vagrant
  - role: cask_install
    package_name: adium
  - role: cask_install
    package_name: appcleaner
  - role: cask_install
    package_name: caffeine
  - role: cask_install
    package_name: dropbox
  - role: cask_install
    package_name: evernote
  - role: cask_install
    package_name: firefox
  - role: cask_install
    package_name: flash
  - role: cask_install
    package_name: google-chrome
  - role: cask_install
    package_name: google-hangouts
  - role: cask_install
    package_name: intellij-idea-ce
  - role: cask_install
    package_name: iterm2
  - role: cask_install
    package_name: mailplane
  - role: cask_install
    package_name: onepassword
  - role: cask_install
    package_name: slate
  - role: cask_install
    package_name: rstudio
  - role: cask_install
    package_name: skitch
  - role: cask_install
    package_name: skype
  - role: cask_install
    package_name: spotify
  - role: cask_install
    package_name: vlc

  # osx config
  - role: dock
    apps:
    - "'~/Applications/Mailplane 3.app'"
    - "'/Applications/Google Chrome.app'"
    - /Applications/Spotify.app
    - /Applications/iTerm.app
    - /Applications/Asana.app
    folders:
    - path: ~/
    - path: /Applications
    - path: ~/Downloads
      sort: datemodified
  - role: cask_install
    package_name: asepsis
  - role: dashboard
    disabled: YES
