---
- name: install {{ package_name }}
  command: brew install {{ package_name }}
  register: result
  ignore_errors: true

- name: upgrade {{ package_name }}
  command: brew upgrade {{ package_name }}
  when: result.stderr.find('Warning') != -1
  ignore_errors: true
