---
dependencies:
  - role: rbenv
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vmware-fusion
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: vagrant-manager
