---
# installs an arbitrary homebrew cask package

- name: tap a repo
  homebrew_tap: tap={{ tap }} state=present
  when: tap is defined

- name: install {{ package_name }}
  homebrew_cask: name={{ package_name }} state=present
